CREATE TABLE DOCUMENTO_GARANTIA (
	ID_DOCUMENTO int IDENTITY(1,1) PRIMARY KEY,
    TIPO_DOCUMENTO nvarchar(10) NULL,
	RUTA_DOCUMENTO nvarchar(500),
	FECHA_REGISTRO datetime NOT NULL
);

ALTER TABLE [dbo].[DOCUMENTO_GARANTIA] ADD  CONSTRAINT [DF_DOCUMENTO_GARANTIA_FECHA_REGISTRO]  DEFAULT ((CURRENT_TIMESTAMP)) FOR FECHA_REGISTRO
GO

--drop table DOCUMENTO_GARANTIA