CREATE TABLE ASIGNACION_PETICION (
	ID_ASIGNACION int,
    CLAVE_ZP int NULL,
	ID_PETICION int NULL,
	ID_PERFIL int NULL,
	DESC_UNIDAD nvarchar(500),
	[ESTATUS] [int] NOT NULL,
	FECHA_REGISTRO datetime NOT NULL
);

ALTER TABLE [dbo].[ASIGNACION_PETICION] ADD  CONSTRAINT [DF_ASIGNACION_PETICION_FECHA_REGISTRO]  DEFAULT ((CURRENT_TIMESTAMP)) FOR FECHA_REGISTRO
GO

ALTER TABLE [dbo].[ASIGNACION_PETICION] ADD  CONSTRAINT [DF_ASIGNACION_PETICION_ESTATUS]  DEFAULT ((1)) FOR [ESTATUS]
GO
--drop table ASIGNACION_PETICION
--select COUNT(distinct ID_ASIGNACION) + 1 ID from ASIGNACION_PETICION
--ID_ASIGNACION int IDENTITY(1, 1) PRIMARY KEY,