CREATE TABLE GARANTIA_PETICION (
	ID_GARANTIA int,
    CLAVE_ZP int NULL,
    ID_PLIEGO int NULL,
	ID_CAT_PETICION int NULL,
	ID_PETICION int NULL,
	DESC_GARANTIA nvarchar(max),
	ID_DOCUMENTO int NULL,
	[ESTATUS] [int] NOT NULL,
	FECHA_REGISTRO datetime NOT NULL
);

ALTER TABLE [dbo].[GARANTIA_PETICION] ADD  CONSTRAINT [DF_GARANTIA_PETICION_FECHA_REGISTRO]  DEFAULT ((CURRENT_TIMESTAMP)) FOR FECHA_REGISTRO
GO

ALTER TABLE [dbo].[GARANTIA_PETICION] ADD  CONSTRAINT [DF_GARANTIA_PETICION_ESTATUS]  DEFAULT ((1)) FOR [ESTATUS]
GO
--drop table GARANTIA_PETICION
--select COUNT(distinct ID_GARANTIA) + 1 ID from GARANTIA_PETICION